### ISSUE TITLE
Getting error while executing task gluster.infra/roles/backend_setup

### ISSUE THREAD

**Issue by rkothiya** [gluster/gluster-ansible-infra#106]
While trying to run gluster-performance-test-suite using centos7 as the control machine, I am getting the following error : 

```
TASK [gluster.infra/roles/backend_setup : Make sure meta and pool pvs exists in volume group] ******************************************************************************
fatal: [server1.com]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
fatal: [server2.com]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
fatal: [server3.com]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
fatal: [server4.com]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
fatal: [server5.com]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
fatal: [server6.com]: FAILED! => {"msg": "dict2items requires a dictionary, got <class 'ansible.template.AnsibleUndefined'> instead."}
```
The pvs are existing on the machine and it is working fine with fedora32, hence I think this is a bug. 
The following gluster-ansible packages were installed on the centos7 machine from the copr repo : 

```
# rpm -qa | grep gluster-ansible 
gluster-ansible-cluster-1.0.1-2.el7.noarch
gluster-ansible-1.0.5-1.el7.noarch
gluster-ansible-maintenance-1.0.1-3.el7.noarch
gluster-ansible-infra-1.0.4-10.el7.noarch
gluster-ansible-repositories-1.0.1-2.el7.noarch
gluster-ansible-features-1.0.5-6.el7.noarch
```

Centos Version : 

```
# cat /etc/redhat-release 
CentOS Linux release 7.4.1708 (Core) 
```

**Important Note:** I am not getting any problems while using fedora32

**Comment by Prajith007007** [comment]
@rkothiya can you share your playbook here? this probably might because centos might not have updated latest builds 
@gobindadas  i think centos might require an updated build gobinda, will check again, but if it requires, im still yet to be sponsored.

**Comment by rkothiya** [comment]
We are trying to run this project, using centos as the control machine:
[Gluster performance test suite](https://github.com/gluster/gluster-performance-test-suite)

**Comment by pkesavap** [comment]
So the centos builds are upto date, the issue was ( ansible --version) was using python2 instead of python3 ,in centos 7 machine, which caused this error

If anyone else faces this issue while using this repo on centos/RHEL7 , do check the python version in ansible (since centos 7 heavly rely on python2 )

closing this issue
