### ISSUE TITLE
[RFE] Use 'gluster_servers' and not 'servers' for hosts inventory 

### ISSUE THREAD

**Issue by mykaul** [gluster/gluster-ansible-infra#14]
Tendrl Ansible (https://github.com/Tendrl/tendrl-ansible/tree/release/1.6.3/ ) use 'gluster_servers' as the list of hosts to have Gluster on as storage servers. Let's be consistent and use it here as well.

**Comment by sac** [comment]
PR: https://github.com/gluster/gluster-ansible-infra/pull/15 should fix this issue.
