### ISSUE TITLE
Support all possible combinations for vdo with thickp and non-vdo with thinp

### ISSUE THREAD

**Issue by gobindadas** [gluster/gluster-ansible-infra#19]
@devyanikota : We have an issue with VDO and thin-pools, hence whenever VDO is enabled on a device, the LV for brick is created as a thick LV. So we need to support vdo with thickp for all device and also non-vdo with thinp.

**Comment by sac-urs** [comment]
Fix https://github.com/gluster/gluster-ansible-infra/commit/07e6947c2007bafcc37 resolves the issue.
