### ISSUE TITLE
All VDO options need to be included in "gluster_infra_vdo" dictionary

### ISSUE THREAD

**Issue by gobindadas** [gluster/gluster-ansible-infra#20]
@devyanikota : Now only three options are included in vdo dictionary like: "name","device" and "logicalsize" and others are global.
The problem is we can't configure other global variables if we have multiple devices.

**Comment by sac** [comment]
https://github.com/gluster/gluster-ansible-infra/commit/07e6947c2007bafcc371143d0d3330c41f959b64 resolves the issue.
