### ISSUE TITLE
Incorrect example @ examples/backend_with_vdo.yml

### ISSUE THREAD

**Issue by mykaul** [gluster/gluster-ansible-infra#30]
```
ykaul@ykaul gluster-ansible-infra]$ find . -name "*.yml" |xargs ansible-lint
Syntax Error while loading YAML.
  did not find expected ',' or '}'

The error appears to have been in '/home/ykaul/github/gluster-ansible-infra/examples/backend_with_vdo.yml': line 22, column 8, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

       - {vgname: 'vg_sdb', thinpoolname: 'foo_thinpool', thinpoolsize: '100G', poolmetadatasize: '16G'
       - {vgname: 'vg_sdc', thinpoolname: 'bar_thinpool', thinpoolsize: '500G', poolmetadatasize: '16G'
       ^ here
```

**Comment by sac** [comment]
PR: https://github.com/gluster/gluster-ansible-infra/pull/28 fixes this issue. It is still under review.
I have removed the examples directory and added playbooks, which is aimed to provide complete playbooks.

**Comment by mykaul** [comment]
@sac  - I'm not sure what the status of this issue is, as the PR seems to be merged.
In the example in the readme itself there's another issue:
```
- {path: '/mnt/thicklv', vgname: 'vg_sdc', lv: 'thinklv_1 }
```
should be:
```
- {path: '/mnt/thicklv', vgname: 'vg_sdc', lv: 'thinklv_1' }
```

**Comment by sac** [comment]
@mykaul the initial issue is resolved.

I have fixed the README typo in this commit: https://github.com/gluster/gluster-ansible-infra/pull/32/commits/472706f0f2a293d7b19d53267b4d259ed0955a53

Actually, there were a few more mistakes I had not updated. I have fixed that as well.
Thank you.

I will close this issue, once the patch is reviewed and merged.
