### ISSUE TITLE
backend setup is not idempotent.

### ISSUE THREAD

**Issue by kristvanbesien** [gluster/gluster-ansible-infra#51]
The backend setup process is not idempotent.

How to reproduce:

- Create a playbook with the gluster.infra role. (and setup the needed variables)
- Run the playbook. Playbook succeeeds.
- Run the playbook a second time. 

Expected result:

- Playbook succeeds second time along

Actual result:

- Playbook fails during the xfs filesystem creation. 

Running the playbook with --skip-tages=fscreate is possible as a workaround, but is not optimal.

**Comment by sac** [comment]
> The backend setup process is not idempotent.
> 

Thanks for reporting this. I was able to debug this issue.
The `force' by default in: https://github.com/gluster/gluster-ansible-infra/blob/master/roles/backend_setup/tasks/fscreate.yml#L25 was causing the issue.

It was forcing the module to re-run the mkfs.xfs whether filesystem was already present or not.

PR: https://github.com/gluster/gluster-ansible-infra/pull/52/files fixes the issue.

**Comment by sac** [comment]
@kristvanbesien request to review https://github.com/gluster/gluster-ansible-infra/pull/52 if you have some time.

**Comment by sac** [comment]
PR: https://github.com/gluster/gluster-ansible-infra/pull/52 resolves this issue.
