### ISSUE TITLE
SELinux glusterd_brick_t fcontext regex

### ISSUE THREAD

**Issue by H0neyBadger** [gluster/gluster-ansible-infra#72]
Hello,
SELinux configuration do not implement a correct regex for glusterd_brick_t fcontext.
https://docs.ansible.com/ansible/latest/modules/sefcontext_module.html
The target should be a regex instead of a path. 

Could you please test and implement the following patch to this playbook ?
https://github.com/gluster/gluster-ansible-infra/blob/master/roles/backend_setup/tasks/mount.yml#L61
```patch
--- a/roles/backend_setup/tasks/mount.yml
+++ b/roles/backend_setup/tasks/mount.yml
@@ -51,7 +51,7 @@

 - name: Set Gluster specific SeLinux context on the bricks
   sefcontext:
-     target: "{{ item.path }}"
+     target: "{{ (item.path | realpath | regex_escape()) + '(/.*)?' }}"
      setype: glusterd_brick_t
      state: present
   with_items: "{{ gluster_infra_mount_devices }}"
```

Due to this bug, the glusterd_brick_t failed to propagate the correct type to our bricks. All our files were flagged as default_t. I prevents glusterd to access some files likes (sockets …) and it raises a big amount of selinux AVC denies alerts. 
Hope this helps,

**Comment by sac** [comment]
@H0neyBadger looks neat. Can you please send a pull request. It is better that way. I can test it out.
