### ISSUE TITLE
Create directory in new bricks

### ISSUE THREAD

**Issue by holmesb** [gluster/gluster-ansible-infra#75]
If you attempt to create a `gluster_volume` pointing at an empty brick created by this role, it will error:

> "volume create: volume_name: failed: The brick storage-server:/data/brickmount is a mount point. Please create a sub-directory under the mount point and use that as the brick directory. Or use 'force' at the end of the command if you want to override this behavior"

I dont want to force.  This behaviour is for a good reason.  If the mount dir exists, but the LV hasn't actually been mounted, the volume will use the local file system instead of the mounted LV.  It should error instead.

I propose adding an `initial_dir` parameter to the `gluster_infra_mount_devices` dict, that if specified, will create this directory in the mounted LV.  It will default to blank to avoid breakages.

Not sure exactly when this sub-dir requirement was added to GlusterFS, I'm using 6.x.

**Comment by sac** [comment]
@holmesb you have to provide a directory that does not exist. gluster will take care of creating it.

For example, if your mount point is /mnt/data and you want to create a volume provide /mnt/data/brick1 for example. gluster will take care of creating brick1 for you.

This requirement was there from a very long time.

**Comment by holmesb** [comment]
Thanks @sac
